### ISSUE TITLE
Heroku App Forbidden Access

### ISSUE THREAD

**Issue by hjy0102** [hjy0102/GTheatre#32]
![screen shot 2017-03-19 at 11 53 10 pm](https://cloud.githubusercontent.com/assets/16708615/24090653/66aa935c-0cff-11e7-9f9c-dbbd7ced1187.png)

So I updated the heroku app with the latest commit 146b3b1 and on LOCAL this works, it's beautiful and everything is fine (PLEASE TELL ME IT'S WORKING FOR EVERYONE ELSE TOO) anyways, once it's on the remote server it doesn't like some of the privacy settings or something because I'm getting access errors.

Hypothesis? ClearDB authentication issues is my best guess =^^= but what do I know. Any other thoughts?

**Comment by jeongwoo511** [comment]
Something to do with Procfile... maybe directory?
