### ISSUE TITLE
Aesthetic header

### ISSUE THREAD

**Issue by hjy0102** [hjy0102/GTheatre#37]
Ok so this isn't a really big issue but can someone do something about the css to make the header not look like this: 
<img width="1239" alt="screen shot 2017-03-20 at 2 47 46 pm" src="https://cloud.githubusercontent.com/assets/16708615/24123348/5f31b3a8-0d7c-11e7-9071-88003c27edae.png">

as you can see, the header has a space from the top and covers some of the text -- I don't like this.

**Comment by seanlennaerts** [comment]
Doesn't look like that for me. What browser are you using?

**Comment by hjy0102** [comment]
Chrome

**Comment by hjy0102** [comment]
Oh you are right it doesn't look like that on Safari
