### ISSUE TITLE
Fix SQL

### ISSUE THREAD

**Issue by seanlennaerts** [hjy0102/GTheatre#40]
We still have issues with the SQL. 

**Bugs found so far**

- [ ] The primary key for plays is HNumber, Title, Ryear but that means we cannot have the same movie playing in the same hall at different times of the day because it would be considered a duplicate entry.

- [ ] Is there a way to make it so that every Movie must have at least one entry in Plays? We don't need movies that don't have showtimes in our theatre.

**Comment by hjy0102** [comment]
Let's discuss the second issue on Saturday.
My suggestion: The Plays schema maybe we should still have start time (STime) as part of the primary key at the least, that way we can have STime NOT NULL meaning all movies have to being playing to be in the database. Also why don't we have dates? like a DAY for when these movies will be playing? didn't we have that in our original ER diagram? @jeongwoo511

**Comment by hjy0102** [comment]
d54828711a92e591ec8c2f3d7277f07a4ffae6f6
